# Generated by Django 4.2.15 on 2025-09-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='authority_level',
            field=models.CharField(choices=[('Responder', 'Responder'), ('User', 'User')], help_text="Defines the user's role in the system.", max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(help_text='Contact number for the user', max_length=15),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
