# Generated by Django 5.2.6 on 2025-09-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_name_for_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='authority_level',
            field=models.CharField(choices=[('Responder', 'Responder'), ('User', 'User'), ('LGU Administrator', 'LGU Administrator')], max_length=20),
        ),
    ]
