# Generated by Django 5.2.4 on 2025-07-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyResponderArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the emergency responder area (e.g., 'District 1', 'City Proper').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the area.')),
                ('polygon_coordinates', models.JSONField(blank=True, help_text='GeoJSON polygon coordinates defining the area boundary.', null=True)),
                ('threshold_level', models.IntegerField(default=5, help_text="Number of reports in this area to trigger 'Bayanihan Act' (community response).")),
            ],
        ),
        migrations.CreateModel(
            name='LGUProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text="Name of the Local Government Unit department (e.g., 'City Disaster Office').", max_length=100)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lgu_profile', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the responder unit (e.g., 'Unit Alpha', 'Fire Truck 1').", max_length=100, unique=True)),
                ('unit_type', models.CharField(choices=[('Fire', 'Fire Department'), ('Police', 'Police Department'), ('Medical', 'Medical/Ambulance'), ('Rescue', 'Rescue Team'), ('Other', 'Other')], help_text='Type of emergency response unit.', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude of the responder unit.', max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude of the responder unit.', max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the unit is currently active/operational.')),
                ('area_of_operation', models.ForeignKey(blank=True, help_text='Primary area this unit operates in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responder_units', to='responders.emergencyresponderarea')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the responder is currently available for dispatch.')),
                ('on_duty_area', models.ForeignKey(blank=True, help_text='The specific area the responder is currently on duty in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='responders.emergencyresponderarea')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_profile', to='accounts.userprofile')),
                ('responder_unit', models.ForeignKey(blank=True, help_text='The responder unit this individual belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='responders.responderunit')),
            ],
        ),
    ]
