# Generated by Django 5.2.4 on 2025-07-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyHotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the hotline (e.g., 'National Police', 'Local Fire Dept').", max_length=100)),
                ('phone_number', models.CharField(help_text='The emergency contact number.', max_length=20)),
                ('is_national', models.BooleanField(default=False, help_text='True if this is a national hotline, False for local.')),
                ('area', models.ForeignKey(blank=True, help_text='The specific area this local hotline serves (if not national).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='responders.emergencyresponderarea')),
            ],
        ),
        migrations.CreateModel(
            name='PublicAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the public announcement.', max_length=200)),
                ('content', models.TextField(help_text='Full content of the announcement or news report.')),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the announcement was published.')),
                ('area', models.ForeignKey(blank=True, help_text='The specific area this announcement is relevant to (if localized).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='responders.emergencyresponderarea')),
            ],
        ),
    ]
